-- Sharanya Properties Hub — sample content seed (generated from /data).
-- Re-runnable: deterministic ids + ON CONFLICT DO NOTHING.
-- Run after schema.sql:  psql "$DATABASE_URL" -f db/seed.sql

BEGIN;

-- Ventures
INSERT INTO ventures (id, slug, name, location, city, type, status, featured, price_label, tagline, summary, extent, plots, size_range, map_query, highlights, amenities, approvals, connectivity, cover_image) VALUES ('serenity-heights', 'serenity-heights', 'SR Serenity Heights', 'Nadergul', 'Hyderabad', 'Villa Plots', 'ONGOING', true, 'Price on request', 'A signature gated layout at Nadergul', 'A meticulously planned, HMDA-approved gated community on the Badangpet–Adibatla main road, offering exclusive villa plots with clear titles, concealed infrastructure and lush landscaping.', NULL, NULL, '152 – 413 Sq. Yds', 'Nadergul, Hyderabad, Telangana', ARRAY['HMDA-approved premium layout with clear titles','Elegant 30 ft concrete roads','Exclusive villa plots from 152 to 413 sq. yds','Concealed underground infrastructure','Two years of professional maintenance support','Loan assistance from leading banks']::text[], ARRAY['Landscaped avenues & curated open spaces','Children''s play zone & lifestyle parks','Underground electricity & drainage','Manicured gardens','Gated entry']::text[], ARRAY['HMDA Approved']::text[], '[{"label":"ORR Raviryal Exit","time":"Minutes away"},{"label":"Rajiv Gandhi Intl. Airport","time":"~30 mins"},{"label":"Adibatla IT / TCS corridor","time":"Nearby"}]'::jsonb, '/ventures/serenity-heights.jpg') ON CONFLICT (id) DO NOTHING;
INSERT INTO ventures (id, slug, name, location, city, type, status, featured, price_label, tagline, summary, extent, plots, size_range, map_query, highlights, amenities, approvals, connectivity, cover_image) VALUES ('sr-eco-park', 'sr-eco-park', 'SR Eco Park', 'Nadergul', 'Hyderabad', 'Open Plots', 'ONGOING', true, 'Price on request', 'An oasis of peace at Nadergul', 'Premium residential plots set across 17.57 acres — a green, family-friendly community with groves, wellness zones and complete underground infrastructure to build homes, lives and legacies.', '17.57 Acres', '225 Plots', '150 – 594 Sq. Yds', 'Nadergul, Hyderabad, Telangana', ARRAY['17.57 acres · 225 plots','Plot sizes from 150 to 594 sq. yds','40 ft and 30 ft CC roads','Compound wall on all sides','24×7 security & provision for Krishna water','Underground sump, electricity & drainage']::text[], ARRAY['Grand entrance plaza','Jogging track & EPDM kids'' play court','Cricket net & badminton court','Meditation & yoga zones','Mango grove & coconut grove','Summer park, party lawn & seating alcoves']::text[], ARRAY['Approved layout']::text[], '[{"label":"Outer Ring Road","time":"Close by"},{"label":"Rajiv Gandhi Intl. Airport","time":"Short drive"},{"label":"Adibatla / Hardware Park","time":"Nearby"}]'::jsonb, '/ventures/sr-eco-park.jpg') ON CONFLICT (id) DO NOTHING;
INSERT INTO ventures (id, slug, name, location, city, type, status, featured, price_label, tagline, summary, extent, plots, size_range, map_query, highlights, amenities, approvals, connectivity, cover_image) VALUES ('sr-infinity-villas', 'sr-infinity-villas', 'SR Infinity Villas', 'Nadergul', 'Hyderabad', 'Villas', 'ONGOING', true, 'Price on request', 'Private villas, club lifestyle', 'A gated enclave of 110 luxury 3 BHK villas across 7.57 acres, where private living and resort-style clubhouse amenities coexist — five minutes from ORR Exit 14.', '7.57 Acres', '110 Villas', '167 – 211 Sq. Yds', 'Nadergul, Hyderabad, Telangana', ARRAY['7.57 acres · 110 luxury villas','3 BHK, G+2 floors','Villa sizes 167 / 183 / 211 sq. yds','Clubhouse with lifestyle amenities','Smooth internal roads & grand entrance']::text[], ARRAY['Clubhouse','Pickleball & multi-purpose court','Outdoor gym','Home theatre','Landscaped surroundings']::text[], ARRAY['Gated villa community']::text[], '[{"label":"ORR Exit 14","time":"5 mins"},{"label":"Rajiv Gandhi Intl. Airport","time":"15 mins"},{"label":"Adibatla (TCS) IT Park","time":"Nearby"},{"label":"Aga Khan Academy","time":"Nearby"}]'::jsonb, '/ventures/sr-infinity-villas.jpg') ON CONFLICT (id) DO NOTHING;
INSERT INTO ventures (id, slug, name, location, city, type, status, featured, price_label, tagline, summary, extent, plots, size_range, map_query, highlights, amenities, approvals, connectivity, cover_image) VALUES ('aero-villas-nadergul', 'aero-villas-nadergul', 'Aero Villas', 'Nadergul', 'Hyderabad', 'Villas', 'ONGOING', false, 'Price on request', 'Premium villas in the airport corridor', 'A premium villa community at Nadergul, positioned along Hyderabad''s fast-growing aerospace and airport corridor with quick access to the Outer Ring Road.', NULL, NULL, NULL, 'Nadergul, Hyderabad, Telangana', ARRAY['Villa community at Nadergul','Airport-corridor location','Quick ORR connectivity']::text[], ARRAY['Gated community','Landscaped avenues','Modern villa design']::text[], ARRAY['Details on request']::text[], '[{"label":"Outer Ring Road","time":"Close by"},{"label":"Rajiv Gandhi Intl. Airport","time":"Short drive"},{"label":"TATA Aerospace / Adibatla","time":"Nearby"}]'::jsonb, '/ventures/aero-villas-nadergul.jpg') ON CONFLICT (id) DO NOTHING;
INSERT INTO ventures (id, slug, name, location, city, type, status, featured, price_label, tagline, summary, extent, plots, size_range, map_query, highlights, amenities, approvals, connectivity, cover_image) VALUES ('sree-city', 'sree-city', 'Sree City', 'Hyderabad', 'Hyderabad', 'Open Plots', 'ONGOING', false, 'Price on request', 'Open plots on a 300  ft road', 'A plotted development laid out along a 300 ft road, planned for connectivity and long-term appreciation. Full specifications are being finalised.', NULL, NULL, NULL, 'Hyderabad, Telangana', ARRAY['Plotted layout on a 300 ft road','Planned for connectivity & appreciation']::text[], ARRAY['Wide internal roads','Planned open spaces']::text[], ARRAY['Details on request']::text[], '[{"label":"300 ft main road frontage","time":"Direct"}]'::jsonb, '/ventures/sree-city.jpg') ON CONFLICT (id) DO NOTHING;
INSERT INTO ventures (id, slug, name, location, city, type, status, featured, price_label, tagline, summary, extent, plots, size_range, map_query, highlights, amenities, approvals, connectivity, cover_image) VALUES ('rock-town-majeedpur', 'rock-town-majeedpur', 'Rock Town', 'Majeedpur', 'Hyderabad', 'Open Plots', 'ONGOING', false, 'Price on request', 'Open plots at Majeedpur', 'An open-plot layout at Majeedpur with a planned road network. Detailed specifications and pricing are available on request.', NULL, NULL, NULL, 'Majeedpur, Hyderabad, Telangana', ARRAY['Open-plot layout at Majeedpur','Planned road network']::text[], ARRAY['Layout roads','Planned infrastructure']::text[], ARRAY['Details on request']::text[], '[{"label":"Majeedpur","time":"Location on request"}]'::jsonb, '/ventures/rock-town-majeedpur.jpg') ON CONFLICT (id) DO NOTHING;
INSERT INTO ventures (id, slug, name, location, city, type, status, featured, price_label, tagline, summary, extent, plots, size_range, map_query, highlights, amenities, approvals, connectivity, cover_image) VALUES ('saffron-skyline', 'saffron-skyline', 'Saffron Skyline', 'Hasthinapuram', 'Hyderabad', 'Apartments', 'UPCOMING', false, 'Price on request', 'Rising near Hasthinapuram', 'A premium development near Hasthinapuram with airport-corridor access via a 30 ft wide approach road. Full details are being finalised — register your interest to be notified.', NULL, NULL, NULL, 'Hasthinapuram, Hyderabad, Telangana', ARRAY['Premium development near Hasthinapuram','30 ft wide approach road','Airport-corridor access']::text[], ARRAY['Planned lifestyle amenities']::text[], ARRAY['Details on request']::text[], '[{"label":"Hasthinapuram","time":"Nearby"},{"label":"Rajiv Gandhi Intl. Airport","time":"Corridor access"}]'::jsonb, '/ventures/saffron-skyline.jpg') ON CONFLICT (id) DO NOTHING;

-- Gallery media
INSERT INTO media (id, url, caption, kind, venture_id, sort_order) VALUES ('media-1', '/ventures/serenity-heights.jpg', 'SR Serenity Heights — gated layout, Nadergul', 'image', (SELECT id FROM ventures WHERE slug='serenity-heights'), 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO media (id, url, caption, kind, venture_id, sort_order) VALUES ('media-2', '/gallery/serenity-heights-2.jpg', 'Serenity Heights — location & highlights', 'image', (SELECT id FROM ventures WHERE slug='serenity-heights'), 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO media (id, url, caption, kind, venture_id, sort_order) VALUES ('media-3', '/ventures/sr-eco-park.jpg', 'SR Eco Park — an oasis of peace', 'image', (SELECT id FROM ventures WHERE slug='sr-eco-park'), 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO media (id, url, caption, kind, venture_id, sort_order) VALUES ('media-4', '/gallery/sr-eco-park-2.jpg', 'SR Eco Park — premium residential plots', 'image', (SELECT id FROM ventures WHERE slug='sr-eco-park'), 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO media (id, url, caption, kind, venture_id, sort_order) VALUES ('media-5', '/gallery/sr-eco-park-3.jpg', 'SR Eco Park — features', 'image', (SELECT id FROM ventures WHERE slug='sr-eco-park'), 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO media (id, url, caption, kind, venture_id, sort_order) VALUES ('media-6', '/gallery/sr-eco-park-4.jpg', 'SR Eco Park — master plan', 'image', (SELECT id FROM ventures WHERE slug='sr-eco-park'), 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO media (id, url, caption, kind, venture_id, sort_order) VALUES ('media-7', '/ventures/sr-infinity-villas.jpg', 'SR Infinity Villas — private villas, club lifestyle', 'image', (SELECT id FROM ventures WHERE slug='sr-infinity-villas'), 6) ON CONFLICT (id) DO NOTHING;
INSERT INTO media (id, url, caption, kind, venture_id, sort_order) VALUES ('media-8', '/gallery/sr-infinity-villas-2.jpg', 'SR Infinity Villas — amenities', 'image', (SELECT id FROM ventures WHERE slug='sr-infinity-villas'), 7) ON CONFLICT (id) DO NOTHING;
INSERT INTO media (id, url, caption, kind, venture_id, sort_order) VALUES ('media-9', '/gallery/sr-infinity-villas-3.jpg', 'SR Infinity Villas — clubhouse living', 'image', (SELECT id FROM ventures WHERE slug='sr-infinity-villas'), 8) ON CONFLICT (id) DO NOTHING;
INSERT INTO media (id, url, caption, kind, venture_id, sort_order) VALUES ('media-10', '/gallery/sr-infinity-villas-8.jpg', 'SR Infinity Villas — villa floor plan', 'image', (SELECT id FROM ventures WHERE slug='sr-infinity-villas'), 9) ON CONFLICT (id) DO NOTHING;
INSERT INTO media (id, url, caption, kind, venture_id, sort_order) VALUES ('media-11', '/ventures/aero-villas-nadergul.jpg', 'Aero Villas — Nadergul', 'image', (SELECT id FROM ventures WHERE slug='aero-villas-nadergul'), 10) ON CONFLICT (id) DO NOTHING;
INSERT INTO media (id, url, caption, kind, venture_id, sort_order) VALUES ('media-12', '/gallery/aero-villas-2.jpg', 'Aero Villas — overview', 'image', (SELECT id FROM ventures WHERE slug='aero-villas-nadergul'), 11) ON CONFLICT (id) DO NOTHING;
INSERT INTO media (id, url, caption, kind, venture_id, sort_order) VALUES ('media-13', '/gallery/aero-villas-3.jpg', 'Aero Villas — layout', 'image', (SELECT id FROM ventures WHERE slug='aero-villas-nadergul'), 12) ON CONFLICT (id) DO NOTHING;
INSERT INTO media (id, url, caption, kind, venture_id, sort_order) VALUES ('media-14', '/ventures/sree-city.jpg', 'Sree City — plotted development', 'image', (SELECT id FROM ventures WHERE slug='sree-city'), 13) ON CONFLICT (id) DO NOTHING;
INSERT INTO media (id, url, caption, kind, venture_id, sort_order) VALUES ('media-15', '/gallery/sree-city-2.jpg', 'Sree City — layout detail', 'image', (SELECT id FROM ventures WHERE slug='sree-city'), 14) ON CONFLICT (id) DO NOTHING;
INSERT INTO media (id, url, caption, kind, venture_id, sort_order) VALUES ('media-16', '/gallery/sree-city-3.jpg', 'Sree City — plan', 'image', (SELECT id FROM ventures WHERE slug='sree-city'), 15) ON CONFLICT (id) DO NOTHING;
INSERT INTO media (id, url, caption, kind, venture_id, sort_order) VALUES ('media-17', '/ventures/rock-town-majeedpur.jpg', 'Rock Town — Majeedpur layout', 'image', (SELECT id FROM ventures WHERE slug='rock-town-majeedpur'), 16) ON CONFLICT (id) DO NOTHING;
INSERT INTO media (id, url, caption, kind, venture_id, sort_order) VALUES ('media-18', '/ventures/saffron-skyline.jpg', 'Saffron Skyline — near Hasthinapuram', 'image', (SELECT id FROM ventures WHERE slug='saffron-skyline'), 17) ON CONFLICT (id) DO NOTHING;

-- Downloads
INSERT INTO download_files (id, label, category, url, venture_id) VALUES ('dl-1', 'SR Serenity Heights — Brochure', 'Brochure', '/downloads/serenity-heights-brochure.pdf', (SELECT id FROM ventures WHERE slug='serenity-heights')) ON CONFLICT (id) DO NOTHING;
INSERT INTO download_files (id, label, category, url, venture_id) VALUES ('dl-2', 'SR Eco Park — Brochure', 'Brochure', '/downloads/sr-eco-park-brochure.pdf', (SELECT id FROM ventures WHERE slug='sr-eco-park')) ON CONFLICT (id) DO NOTHING;
INSERT INTO download_files (id, label, category, url, venture_id) VALUES ('dl-3', 'SR Infinity Villas — Brochure', 'Brochure', '/downloads/sr-infinity-villas-brochure.pdf', (SELECT id FROM ventures WHERE slug='sr-infinity-villas')) ON CONFLICT (id) DO NOTHING;
INSERT INTO download_files (id, label, category, url, venture_id) VALUES ('dl-4', 'Aero Villas — Brochure', 'Brochure', '/downloads/aero-villas-nadergul-brochure.pdf', (SELECT id FROM ventures WHERE slug='aero-villas-nadergul')) ON CONFLICT (id) DO NOTHING;
INSERT INTO download_files (id, label, category, url, venture_id) VALUES ('dl-5', 'Saffron Skyline — Brochure', 'Brochure', '/downloads/saffron-skyline-brochure.pdf', (SELECT id FROM ventures WHERE slug='saffron-skyline')) ON CONFLICT (id) DO NOTHING;
INSERT INTO download_files (id, label, category, url, venture_id) VALUES ('dl-6', 'Sree City — Brochure', 'Brochure', '/downloads/sree-city-brochure.pdf', (SELECT id FROM ventures WHERE slug='sree-city')) ON CONFLICT (id) DO NOTHING;
INSERT INTO download_files (id, label, category, url, venture_id) VALUES ('dl-7', 'Sree City — Layout (300 ft road)', 'Layout', '/downloads/sree-city-layout.pdf', (SELECT id FROM ventures WHERE slug='sree-city')) ON CONFLICT (id) DO NOTHING;
INSERT INTO download_files (id, label, category, url, venture_id) VALUES ('dl-8', 'Rock Town — Layout', 'Layout', '/downloads/rock-town-majeedpur-layout.pdf', (SELECT id FROM ventures WHERE slug='rock-town-majeedpur')) ON CONFLICT (id) DO NOTHING;

-- Testimonials
INSERT INTO testimonials (id, name, location, project, rating, quote, sort_order) VALUES ('tm-1', 'Rajesh K.', 'Hyderabad', 'SR Eco Park', 5, 'The clarity on titles and approvals made the decision easy. Registration was smooth and the layout is exactly as shown.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO testimonials (id, name, location, project, rating, quote, sort_order) VALUES ('tm-2', 'Sowmya R.', 'Bengaluru', 'SR Serenity Heights', 5, 'I was investing from another city, so transparency mattered most. Every question was answered clearly over WhatsApp before I visited.', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO testimonials (id, name, location, project, rating, quote, sort_order) VALUES ('tm-3', 'Imran S.', 'Hyderabad', 'SR Infinity Villas', 4, 'The location near ORR Exit 14 sold me. Good connectivity and the clubhouse plans look genuinely well thought out.', 2) ON CONFLICT (id) DO NOTHING;

-- FAQs
INSERT INTO faqs (id, question, answer, sort_order) VALUES ('faq-1', 'Are Sharanya Properties Hub layouts approved?', 'Our flagship layouts such as SR Serenity Heights are HMDA-approved with clear titles. Approval status for each venture is listed on its project page — ask us on WhatsApp for the specific approval documents of any project.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, question, answer, sort_order) VALUES ('faq-2', 'Which areas do you develop in?', 'We focus on Hyderabad''s high-growth ORR corridor — currently Nadergul, Majeedpur, Hasthinapuram and surrounding areas with strong connectivity to the Outer Ring Road, Rajiv Gandhi International Airport and the Adibatla IT/aerospace hub.', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, question, answer, sort_order) VALUES ('faq-3', 'What plot sizes are available?', 'Plot and villa sizes vary by project — for example, SR Eco Park offers 150–594 sq. yds and SR Infinity Villas offers 167–211 sq. yd villas. See each project page for its size range.', 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, question, answer, sort_order) VALUES ('faq-4', 'Do you offer home-loan assistance?', 'Yes. Several of our layouts have tie-ups with leading banks for loan assistance. Share your requirement and we''ll guide you on eligible options.', 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, question, answer, sort_order) VALUES ('faq-5', 'How do I book a site visit?', 'Call or WhatsApp us on +91 94937 02929, or submit an enquiry on any project page. We''ll arrange a convenient site visit and walk you through the layout, pricing and documentation.', 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, question, answer, sort_order) VALUES ('faq-6', 'Is the price fixed or negotiable?', 'Pricing depends on plot size, location within the layout and current availability. Contact us for the latest per-sq-yd pricing and any ongoing offers for a specific venture.', 5) ON CONFLICT (id) DO NOTHING;

-- Global site settings
INSERT INTO site_settings (id, data) VALUES ('site', '{"name":"Sharanya Properties Hub","legalName":"Sharanya Properties Hub Hyderabad","tagline":"HMDA & DTCP approved plotted developments across Hyderabad","description":"Sharanya Properties Hub develops premium, approved open plots and villa layouts across Hyderabad''s ORR growth corridor — clear titles, gated infrastructure, and locations built for long-term value.","url":"https://sharanyaproperties.in","city":"Hyderabad","region":"Telangana","country":"IN","phone":"+919493702929","phoneDisplay":"+91 94937 02929","whatsapp":"919493702929","email":"info@sharanyaproperties.in","address":"Nadergul, Hyderabad, Telangana","whatsappMessage":"Hi Sharanya Properties Hub, I''d like details about your plotted projects.","social":{"instagram":"","facebook":"","youtube":""}}'::jsonb) ON CONFLICT (id) DO NOTHING;

COMMIT;
